runtime: java11
instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 50

handlers:
- url: /.*
  script: auto
  secure: always

env_variables:
  JAVA_TOOL_OPTIONS: "-XX:MaxRAM=256m" 